### ISSUE TITLE
ModuleNotFoundError: No module named 'past'

### ISSUE THREAD

**Issue by cwirz** [DEKHTIARJonathan/pyEthOS#1]
Seems like the pypi version does not install the future package...

**Comment by cwirz** [comment]
Seems like the pypi version does not install the future package...

**Comment by DEKHTIARJonathan** [comment]
You are correct and it should now be fixed with the 1.4.1 version released ;)

May I ask you where you found this lib ?

**Comment by cwirz** [comment]
What lib do you mean?

**Comment by cwirz** [comment]
Btw: validators package was also not installed on version 1.4.0

**Comment by DEKHTIARJonathan** [comment]
Yeap I figured it out too. It was fixed in 1.4.1.

I mean this repository, how did you find it ?

**Comment by cwirz** [comment]
Using google. Tried to find the best way how to get all ETH transactions from a wallets public address...

**Comment by DEKHTIARJonathan** [comment]
Oh nice ;) If you want to improve the lib, do not hesitate to send a Pull Request ;)
I can't implement everything, I just wait for feature request/use cases.
